Repository softhsm/SoftHSMv2, pull requests merged in 2024-11, with the labels that each got.

#733 Add GitHub Actions CI
  .github/workflows/ci.yml
  src/lib/test/CMakeLists.txt
Labels: important

#766 Update Github actions
  .github/workflows/ci.yml
Labels: ci

#762 fix: Use CMAKE_SHARED_LIBRARY_SUFFIX instead of hardcode .so
  CMakeLists.txt
Labels: small

#760 Fix a typo in `Mecahnisms`
  src/lib/SoftHSM.cpp
  src/lib/SoftHSM.h
Labels: small
